name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix flake check
      - run: nix build .#homeConfigurations.gabriel.activationPackage --no-link
      - run: nix build '.#homeConfigurations."gsantos@lenovo".activationPackage' --no-link
